src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private ?string $email;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     *
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity=Account::class, mappedBy="linkedTo", orphanRemoval=true)
     */
    private $accounts;

    /**
     * @ORM\OneToMany(targetEntity=TitleHistory::class, mappedBy="creator", orphanRemoval=true)
     */
    private $titleHistory;

    /**
     * @ORM\Column(type="datetime_immutable", options={"default": "CURRENT_TIMESTAMP"})
     * @Gedmo\Timestampable(on="create")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     * @Gedmo\Timestampable(on="update")
     */
    private $updatedAt;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="moderatorOf")
     * @ORM\JoinTable(name="moderators",
     *      joinColumns={@ORM\JoinColumn(name="admin_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="moderator_id", referencedColumnName="id")}
     *      )
     */
    private $moderators;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="moderators")
     */
    private $moderatorOf;

    public function __toString(): string
    {
        return $this->getUserIdentifier();
    }

    public function __construct()
    {
        $this->accounts = new ArrayCollection();
        $this->titleHistory = new ArrayCollection();
        $this->moderators = new ArrayCollection();
        $this->moderatorOf = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Account[]
     */
    public function getAccounts(): Collection
    {
        return $this->accounts;
    }

    public function addAccount(Account $account): self
    {
        if (!$this->accounts->contains($account)) {
            $this->accounts[] = $account;
            $account->setLinkedTo($this);
        }

        return $this;
    }

    public function removeAccount(Account $account): self
    {
        if ($this->accounts->removeElement($account)) {
            // set the owning side to null (unless already changed)
            if ($account->getLinkedTo() === $this) {
                $account->setLinkedTo(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TitleHistory[]
     */
    public function getTitleHistory(): Collection
    {
        return $this->titleHistory;
    }

    public function addTitleHistory(TitleHistory $titleHistory): self
    {
        if (!$this->titleHistory->contains($titleHistory)) {
            $this->titleHistory[] = $titleHistory;
            $titleHistory->setCreator($this);
        }

        return $this;
    }

    public function removeTitleHistory(TitleHistory $titleHistory): self
    {
        if ($this->titleHistory->removeElement($titleHistory)) {
            // set the owning side to null (unless already changed)
            if ($titleHistory->getCreator() === $this) {
                $titleHistory->setCreator(null);
            }
        }

        return $this;
    }

    public function getLastTitles(): Collection
    {
        $criteria = Criteria::create()
            ->orderBy(['createdAt' => 'DESC'])
            ->setMaxResults(10);

        return $this->titleHistory->matching($criteria);
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getModerators(): Collection
    {
        return $this->moderators;
    }

    public function addModerator(self $moderator): self
    {
        if (!$this->moderators->contains($moderator)) {
            $this->moderators[] = $moderator;
        }

        return $this;
    }

    public function removeModerator(self $moderator): self
    {
        $this->moderators->removeElement($moderator);

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getModeratorOf(): Collection
    {
        return $this->moderatorOf;
    }

    public function addModeratorOf(self $moderatorOf): self
    {
        if (!$this->moderatorOf->contains($moderatorOf)) {
            $this->moderatorOf[] = $moderatorOf;
            $moderatorOf->addModerator($this);
        }

        return $this;
    }

    public function removeModeratorOf(self $moderatorOf): self
    {
        if ($this->moderatorOf->removeElement($moderatorOf)) {
            $moderatorOf->removeModerator($this);
        }

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\StreamInfoType;
use App\Provider\AbstractPlatformProvider;
use App\Repository\PlatformRepository;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    private PlatformRepository $platformRepository;

    public function __construct(PlatformRepository $platformRepository)
    {
        $this->platformRepository = $platformRepository;
    }

    /**
     * @Route("/", name="home")
     */
    public function index(): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'platforms' => $this->platformRepository->findAll()
        ]);
    }

    /**
     * @Route("/update-stream-infos", name="updateStreamInfos")
     */
    public function updateStreamInfos(Request $request, LoggerInterface $logger, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(StreamInfoType::class);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $streamInfos = $form->getData();

            // TODO : Add title and category to session so that it stays even after refresh of the page :)

            /** @var User $user */
            $user = $this->getUser();
            foreach ($user->getAccounts() as $account) {
                if (class_exists($account->getPlatform()->getProvider())) {
                    /** @var AbstractPlatformProvider $provider */
                    $provider = new ($account->getPlatform()->getProvider())($em, $logger);
                    if ($provider->updateStreamTitleAndCategory($account, $streamInfos['title'], $streamInfos['category'])) {
                        $this->addFlash('titleUpdate-success', 'Successfully updated title for ' . $account->getPlatform()->getName());
                    } else {
                        $this->addFlash('titleUpdate-failure', 'Failed to update title for ' . $account->getPlatform()->getName());

                    }
                } else {
                    $logger->error('This provider doesn\'t exist.');
                    $this->addFlash('titleUpdate-failure', 'Update title feature does not exist yet for ' . $account->getPlatform()->getName());
                }
            }
        }

        return $this->render('home/update-stream-infos.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block description %}{{ "home.slogan"|trans }} {{ "home.valueProposition.title"|trans }}{% endblock %}

{% block body %}
    <section class="relative block">
        <div class="container mx-auto px-4">
            <div class="flex flex-wrap text-center justify-center">
                <div class="w-full lg:w-6/12 px-4">
                    <img src="{{ asset('favicon.svg') }}" class="m-auto" width="150" height="150"
                         alt="Logo of multistream tools"/>
                    <h1 class="text-4xl font-semibold">Multistream Tools</h1>
                    <h2 class="text-2xl">{{ "home.slogan"|trans }}</h2>
                    <p class="text-lg leading-relaxed mt-4 mb-4">
                        {{ "home.valueProposition.title"|trans }}
                    </p>
                </div>
            </div>
            <div class="flex flex-wrap mt-12 justify-center">
                <div class="w-full lg:w-3/12 px-4 text-center">
                    <div class="p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"/>
                        </svg>
                    </div>
                    <h6 class="text-xl mt-5 font-semibold">
                        {{ "home.valueProposition.manage.title"|trans }}
                    </h6>
                    <p class="mt-2 mb-4">
                        {{ "home.valueProposition.manage.detail"|trans }}
                    </p>
                </div>
                <div class="w-full lg:w-3/12 px-4 text-center">
                    <div class="p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                  d="M2.166 4.999A11.954 11.954 0 0010 1.944 11.954 11.954 0 0017.834 5c.11.65.166 1.32.166 2.001 0 5.225-3.34 9.67-8 11.317C5.34 16.67 2 12.225 2 7c0-.682.057-1.35.166-2.001zm11.541 3.708a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                                  clip-rule="evenodd"/>
                        </svg>
                    </div>
                    <h5 class="text-xl mt-5 font-semibold">
                        {{ "home.valueProposition.safe.title"|trans }}
                    </h5>
                    <p class="mt-2 mb-4">
                        {{ "home.valueProposition.safe.detail1"|trans }}
                        <a href="https://oauth.net/2/" target="_blank" rel="noopener"><strong>OAuth</strong></a>
                        {{ "home.valueProposition.safe.detail2"|trans }}
                    </p>
                </div>
                <div class="w-full lg:w-3/12 px-4 text-center">
                    <div class="text-blueGray-800 p-3 w-12 h-12 shadow-lg rounded-full bg-white inline-flex items-center justify-center">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                  d="M4 2a2 2 0 00-2 2v11a3 3 0 106 0V4a2 2 0 00-2-2H4zm1 14a1 1 0 100-2 1 1 0 000 2zm5-1.757l4.9-4.9a2 2 0 000-2.828L13.485 5.1a2 2 0 00-2.828 0L10 5.757v8.486zM16 18H9.071l6-6H16a2 2 0 012 2v2a2 2 0 01-2 2z"
                                  clip-rule="evenodd"/>
                        </svg>
                    </div>
                    <h5 class="text-xl mt-5 font-semibold">{{ "home.valueProposition.dock.title"|trans }}</h5>
                    <p class="mt-2 mb-4">
                        {{ "home.valueProposition.dock.detail1"|trans }} <strong>OBS
                            dock</strong> {{ "home.valueProposition.dock.detail2"|trans }}
                    </p>
                </div>
            </div>

            <div class="flex flex-wrap text-center justify-center">
                <div class="w-full lg:w-6/12 px-4">
                    <p class="text-lg leading-relaxed mt-4 mb-4 text-blueGray-400">
                        {{ "home.improve"|trans }}
                        <a
                                href="https://github.com/artandor/multistream-tools/issues" target="_blank"
                                rel="noopener">
                            <svg xmlns="http://www.w3.org/2000/svg" class="inline" width="24" height="24"
                                 viewBox="0 0 24 24">
                                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/>
                            </svg>
                        </a>
                    </p>
                </div>
            </div>

        </div>
    </section>


    {{ include('fragments/_platforms.html.twig', {platforms: platforms}) }}
{% endblock %}

templates/home/update-stream-infos.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {% form_theme form 'tailwind_2_layout.html.twig' %}

    {% set formTheme = {
        row_class: 'mb-4',
        label_class: 'block text-gray-700 text-sm font-bold mb-2',
        error_item_class: 'text-red-500 text-xs italic',
        widget_class: 'shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline',
        widget_disabled_class: 'border-dashed text-gray-200',
        widget_errors_class: 'border-double border-red-500 bg-red-50',
    } %}

    {% if not app.request.get('overlay') %}
        <h2 class="text-2xl font-extrabold text-gray-900">{% trans %}stream.update{% endtrans %}</h2>
    {% endif %}

    <div class="w-full">
        {% if not app.request.get('overlay') %}
            <p>{% trans %}stream.youtube.note{% endtrans %}</p>
        {% endif %}

        {# read and display several types of flash messages #}
        {% for label, messages in app.flashes(['titleUpdate-success', 'notification']) %}
            {% for message in messages %}
                <div class="flash-message text-center py-4 lg:px-4">
                    <div class="p-2 bg-indigo-800 items-center text-indigo-100 leading-none lg:rounded-full flex lg:inline-flex"
                         role="alert">
                        <span class="flex rounded-full bg-indigo-500 uppercase px-2 py-1 text-xs font-bold mr-3">Updated</span>
                        <span class="font-semibold mr-2 text-left flex-auto">{{ message }}</span>
                    </div>
                </div>

            {% endfor %}
        {% endfor %}

        {# read and display several types of flash messages #}
        {% for label, messages in app.flashes(['titleUpdate-failure']) %}
            {% for message in messages %}
                <div class="flash-message text-center py-4 lg:px-4">
                    <div class="p-2 bg-yellow-500 items-center text-indigo-100 leading-none lg:rounded-full flex lg:inline-flex"
                         role="alert">
                        <span class="flex rounded-full bg-red-500 uppercase px-2 py-1 text-xs font-bold mr-3">Error</span>
                        <span class="font-semibold mr-2 text-left flex-auto">{{ message }}</span>
                    </div>
                </div>

            {% endfor %}
        {% endfor %}

        {% if title_history.count %}
            <div class="my-4">
                <label for="titleHistory">{{ "stream.lastTitles"|trans }}</label>
                <select id="titleHistory"
                        class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
                    <option></option>
                    {% for title in title_history %}
                        <option data-title="{{ title.title }}" data-category="{{ title.category }}">{{ title }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}

        <div class="w-full">
            {{ form_start(form, {'attr': {'id': 'streamInfosForm'}}) }}

            {{ form_errors(form) }}

            {% if form.account is defined %}
                {{ form_row(form.account, formTheme) }}
            {% endif %}
            {{ form_row(form.title, formTheme) }}
            {{ form_row(form.category, formTheme) }}
            {{ form_row(form.submit, {'attr': {'class': 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline'}}) }}

            {{ form_end(form) }}

            {% if not app.request.get('overlay') %}
                <div class="mt-3">
                    <p>{% trans %}dock.createUrl{% endtrans %}
                        <a href="{{ url('updateStreamInfos', {'overlay': 'true'}) }}">
                            {{ url('updateStreamInfos', {'overlay': 'true'}) }}
                        </a>
                    </p>
                </div>
            {% endif %}
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script>
        window.addEventListener('load', function () {
            setTimeout(function () {
                let elements = document.getElementsByClassName('flash-message');
                for (let i = 0; i < elements.length; i++) {
                    elements.item(i).style.display = "none"
                }
            }, 3000)

            document.getElementById('titleHistory').addEventListener('change', (event) => {
                const selectedOption = event.target.options[event.target.selectedIndex];
                const form = document.getElementById('streamInfosForm');
                form.elements['stream_info[title]'].value = selectedOption.getAttribute('data-title');
                form.elements['stream_info[category]'].value = selectedOption.getAttribute('data-category');
            })
        }, false);
    </script>
{% endblock %}